### ISSUE TITLE
Request: Original Budgeted Amount

### ISSUE THREAD

**Issue by dannyhanes** [wxt9861/ynab#13]
In addition to importing the amount I have left in my budget, I would love to see it also include the original budgeted amount. 

This way I can create my budgets in YNAB and have my custom bar-card update automatically with the correct graph information. 

And example of this is below. 
```
type: custom:bar-card
entities:
  - entity: sensor.template_ynab_groceries
    unit_of_measurement: $
    icon: mdi:cart
    severity:
      - from: '0'
        to: '100'
        color: rgba(222,91,107,1)
      - from: '101'
        to: '300'
        color: var(--label-badge-yellow)
      - from: '301'
        color: var(--label-badge-green)
    min: '0'
    max: '500'
```

Ideally, I want the `max` value to be imported as well, with that being what I had originally budgeted.
